FROM node

# to properly install node-gyp package
ENV USER root

# so that npm installs not into the code path, so we can share this directory and still have npm_modules not shared
RUN npm install --global yarn
RUN mkdir -p /install/ 
COPY ./package.json /install/package.json 
WORKDIR /install
RUN yarn 

# Create app directory
RUN mkdir -p /usr/src/app

# the .dockerignore file is configured to ignore node_modules and other unnecessary files.
WORKDIR /usr/src/app/
COPY . /usr/src/app/

# In case the image is built with docker build command we need to make the node_modules available
EXPOSE 7000
CMD ["npm", "run", "dev"]